### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/tuning-workbench-synth#10]
#1 About, Export, Load SCL appear to be dead; however dragging dropping works
#2 pitch bend maxes at 10
#3 Reset button works however the Apply SCL/KBM do not appear to

**Comment by baconpaul** [comment]
Your first item is #6 
Your second is #4 
but I don't understand your third. Why doesn't the button work?

**Comment by baconpaul** [comment]
Confirmed on slack that the third is deactivating due to edits and stuff and it's all cool so closing this one as dups.

Thanks!!
