### ISSUE TITLE
Sine VCO set to max on re-opening plugin window

### ISSUE THREAD

**Issue by bgins** [surge-synthesizer/tuning-workbench-synth#101]
A gif shows it well:

![sine-reset](https://user-images.githubusercontent.com/7957636/76373756-8a50fc80-62fe-11ea-8ba8-2c93e902a11e.gif)

This happens with the VST2 in Bitwig on Ubuntu 18.04. I did not observe the same behavior in the standalone.

**Comment by baconpaul** [comment]
In (sort of) good news, it doesn't happen with bitwig mac vst3

**Comment by baconpaul** [comment]
Nor does it happen mac reaper vst2

**Comment by bgins** [comment]
Are you able to reproduce with bitwig mac vst2? @tank-trax are you able to reproduce this in any your environments?

**Comment by baconpaul** [comment]
I will try bitwig linux vst2 next. (My bitwig didn't seem to scan vst2 on my mac and I didn't want to screw with it)

**Comment by bgins** [comment]
Yep, that did it. Thanks!
