### ISSUE TITLE
The Desktop version doesn't see my audio interface

### ISSUE THREAD

**Issue by Marc-Winner** [surge-synthesizer/tuning-workbench-synth#139]
With Focusrite Scarlett Solo only audio output is seen, but I can't choose neither my audio interface as audio device type, not ASIO4ALL which is usually is option.

**Comment by baconpaul** [comment]
Unfortunately, the ASIO client API is not compatible with binary distributed GPL3 software. I asked Steinberg about it here.

https://forums.steinberg.net/t/asio-license-and-open-source-software/696630

If you want standalone and ASIO, you would need to assent to the ASIO license yourself and then build a version. I have not modified the TWS CMake file to do that (but did with surge). If you are interested in that, please reopen the issue and I can modify the documentation and the like, but the binary distribution using ASIO is, unfortunately, something we can’t fix.
