### ISSUE TITLE
Hi there, I'm not an ubuntu expert but I got 'fatal error: jack/jack.h:, just wondered if you have any ideas ;D

### ISSUE THREAD

**Issue by siva-shambo** [surge-synthesizer/tuning-workbench-synth#141]
/tuning-workbench-synth/lib/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp:142:12: fatal error: jack/jack.h: No such file or directory
  142 |   #include <jack/jack.h>
      |            ^~~~~~~~~~~~~

Just thought I'd let you know as it might be something with newer versions of Ubuntu, I'm running Ubuntu Studio 20 LTS,
I looked online for the error and installed libjack0

sudo apt install libjack0

but I still go the same error so eh if this is helpful and I would really like to try out the tuning synth though I know you could be busy, thanks for your work I use Surge and eh it's BOSS!!!

Have a fun day!

Siva ;D

**Comment by baconpaul** [comment]
You need to install libjack-dev also

https://github.com/surge-synthesizer/tuning-workbench-synth/blob/0bce695a0c483f29e3d5d8c0d824b240184b6dc4/azure-pipelines.yml#L35

there’s the full list!

If that works pls close the issue and if not we can ponder. I build ubuntu 20 all the time with that apt list tho so should be good

**Comment by siva-shambo** [comment]
Thanks for your prompt reply, I forgot to mention that I did install libjack-dev, it was late last night but I will install the dependencies list you sent me and thanks for that ;o)
I'll let you know,
Happy Friday!!! ;o)

**Comment by baconpaul** [comment]
great please do let us know.

oh after you install libjack-dev and the like you probably want to blow away and re-cmake the build folder too since it may have a stale cached reference.

**Comment by siva-shambo** [comment]
Hi Paul, 
Tell you what, I'm going to leave it for now as it's a lot for my head and I realized I can play around with the tuning in the normal Surge synth, which is amazing, for now, as you know Ubuntu can be a bit quirky and although I'm not a complete newbie I think I have enough to learn atm as it is ;D
I did get the snap version of cmake and it gave errors on a few packages (not just the tuning-synth) so just sp not to crash my PC atm I'll close this thread and say hi again when I give it another go, have a great week end!!! Namaste! ;o)

**Comment by baconpaul** [comment]
Great! Enjoy using surge!
