### ISSUE TITLE
Feature Request: TUN file support

### ISSUE THREAD

**Issue by smadgerano** [surge-synthesizer/tuning-workbench-synth#142]
Loving this and the features inside this, but I'm having trouble converting the SCL or KBM format files to the TUN format my synth supports, it would be great to have native import and export of TUN files if possible.

**Comment by baconpaul** [comment]
Hi!

we don’t plan to add tun support sorry but if by “my synth” you mean “a synth I wrote” you can use our tuning library to add scl/kbm support 

tun v1 (a simple list of keys and frequencies) would be a pretty simple exporter for the tuning library but the tun spec beyond that has a bunch of complexity hence the hesitation

Oh also most of the tuning workbench features are in the upcoming version of surge also! 

Which synth are you trying to export to?

**Comment by smadgerano** [comment]
That's cool, just thought I'd ask in case it was on the radar :)

I'm using MSoundFactory, from Melda, not my "own" synth.......yet anyway. But I thnk I've found an SCL file for the same tuning I was using so I think I can get by and use a converter somewhere.

Loving all of this, keep up the good work and thanks for the response.

**Comment by baconpaul** [comment]
Cool

As a plug, ODDSound MTS-ESP has done the work to support lots of formats, and Surge works with that, if that's your cup of tea. Great team and great software. But it is a paid for product not free.
