### ISSUE TITLE
Not building on Arch and OpenSUSE

### ISSUE THREAD

**Issue by waddafunk** [surge-synthesizer/tuning-workbench-synth#147]
Currently the synth does not build on Arch and OpenSUSE out of the box since support for gcc 12 has been [added](https://github.com/juce-framework/JUCE/commit/ce8aff22c31c4d932a8414bc6f6185381dc970db) in JUCE 7.

Git submodules initiated the JUCE repo pointing to JUCE 6, by changing the repo to the latest JUCE 7 release I was able to build. 

I am using Manjaro but this should be a problem for every Arch and OpenSUSE user, since the default for these systems is gcc 12 guessing from [this](https://forum.juce.com/t/fixed-juceaide-fails-with-gcc12/51545) thread.

**Comment by baconpaul** [comment]
The juce 6 submodule surge ships with has that diff included. 

https://github.com/surge-synthesizer/JUCE/commits/3d663fad37799a8c0091a7e60da220adb469f608

so unless you have an error message or somehow didn’t use our submodules I’m not sure why you think the diff isn’t included

**Comment by baconpaul** [comment]
Oh this is TWS not surge duh sorry.

**Comment by baconpaul** [comment]
TWS will be fine with juce 7 - we should just update the submodule. Sorry for reading the repo wrong!

**Comment by waddafunk** [comment]
No problem, happy I could help!

**Comment by baconpaul** [comment]
(The reason its been so long since an update, by the way, is we put all the features from TWS into Surge XT so most users have migrated there. But a submodule update is easy and I'll do it this AM for users of the synth in old sessions and stuff)

**Comment by baconpaul** [comment]
OK all updated. Thanks for flagging it and sorry again for reading the wrong repo! Too many projects here :)

Enjoy
