### ISSUE TITLE
Add a per-note editor

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/tuning-workbench-synth#16]
I'm just gonna keep my work list up here as checkmarks for now

- [ ] Graph
  - [x] Graph updates with scale edits
  - [x] Graph makes some sense
  - [x] Drag on the graph
  - [x] notes playing on the graph
  - [ ] drag through center 
  - [x] colors on graph; outline line when midi note is playing; use yellow/blue for sharp/flat
  - [x] modes in the graph
      - [x] uniform spokes with dots in/out with connectors
      - [ ] uniform spokes with dots left/right with connectors
      - [x] non-uniform spokes with labels
- [ ] UI changes
   - [x] Non-modal
   - [x] Drag an SCL onto it
   - [ ] Blind Tasting Mode
   - [ ] Centify button on ratios
   - [x] Bugs now we are non-modal
- [x] Playing note lights up scale note (requires tuning lib to tell me scale position for midi note)
- [ ] Add generators
   - [x] EDN-M
   - [ ] Stretch the Scale
- [ ] Other Analytics
  - [ ] Matrix View
  - [ ] Linear Scale view
- [x] Usability
  - [x] init saw as well as sine Jacky mentions below

**Comment by baconpaul** [comment]
For scales this will include generator as referenced in #25

**Comment by bgins** [comment]
TWS Advanced Scale Editor @c9cee658 testing notes:

- The knobs work the way I would expect. It took me a moment to understand how changing period changes all of the notes except those within one period above the middle note. Makes sense and seems right.
- I loaded ED3-12 and recreated it from scratch starting from ED2-12. The results the Tuning table are exactly the same.
- The way the Analytics circle show frequencies is different from how Bitwig or Cantor (the iOS app I mentioned previously) display it. Whereas Bitwig and Cantor change the distance between the lines, we keep each of the lines static and move the orange-red circles to adjust the tuning (I am assuming we will drag these). I like this idea and I think it likely gives more precision and makes more sense for a draggable UI (how would you grab one line when it is very close to another line?) 
- In a way, moving these little orange-red circles is like tuning a stringed instrument with a tuning peg
- It looks to me like the position of the orange-red circles indicates the distance from ED (the white circle on the outside). I wonder if it would also be possible to express the distance between the notes of the scale on this circle. For example, the white circle might indicate 1/1 and the center of the circle the period.
- It would also be neat if the Scale column lit up the way the tuning table does when you play a matching note in the scale (and maybe the corresponding "string" on the circle as well?)
- Awesome work on this! It's fun to dynamically adjust the tunings and hear the results right away!

**Comment by baconpaul** [comment]
Notes from @JackyLigon

Analytics Circle
I’m not certain this is working as it should, and when I make changes to the Scale Tones, they do not seem reflected in the circle in an expected way.
 
I can see that the orange dots move a little, but their movements are not easily detected while retuning, nor do they seem to accord much with what’s happening with interval retuning in the Scale Tones section. We may need to compare some screenshots and notes on this facet of the UI.
 
Q: Should I assume that the top vertical line is the 1/1, as in Pianoteq and Scala’s tone circles?
 
Addendum: I can see now that the tone-circle only updates when I close and reopen the ASE dialog. If possible, it would be extremely useful if that updated in real-time, to reflect visually the custom retuning.
 
Some suggestions
A small suggestion is to make the Advanced Scale Editor dialog a SCL-KBM drag-and-drop area, so that one can change them, without having to close the dialog and drop them onto the main UI.
 
Also, make both the Advanced Scale Editor dialog, and the main TWS UI, floating, independent and active at the same time, if possible. There were some points in testing, where it would’ve been nice to grab and move the scrollbar to another location in the mapping on the Tuning display of the main UI, but this isn’t possible while the ASE is open.
 
Take the INIT Sine preset, lower the sine, and turn the Saw all the way up, making an additional INIT Saw preset. This is another important preset to have for retuning with a harmonic series timbre. I can make it if you like.

Oh, one more important thing I failed write above, which I'll add in an edit, is that it might also be useful to have a simple stretch/compress octave tuning feature as an option. It might be a switchable mode, where one could retune the repeat interval (or period) of the tuning, and uniformly stretch or compress the entire tuning, which would enable doing something akin to a synthesizer variant of piano stretch-tuning, although with the piano, the stretch is applied over the range of the keyboard to compensate for the intrinsic inharmonicity of piano strings.
But here, just being able to retune the octave flat or sharp, and have the entire tuning proportionally stretch/compress would be a very useful option.

A potentially fun extrapolation of the TWS ASE, would be to implement blind testing functionality: while in the blind-testing mode, one could hide the cents values, tune by ear to what sounds good, then at the end, unhide the Scale Tones to reveal one’s choices; kind of like a microtuning game of a sort. In the blind-testing mode, it’s only the musician, and their ears making the tuning choices. (edited)

**Comment by baconpaul** [comment]
OK I broke the remaining bits here into separate issues. Closing this one.
