### ISSUE TITLE
Apply SCL crashes the synth when SCL File is empty

### ISSUE THREAD

**Issue by bgins** [surge-synthesizer/tuning-workbench-synth#31]
When I delete all of the text from the SCL File text editor and click on Apply SCL the plugin crashes. With the standalone version run from a terminal, I get a `Floating point exception (core dumped)` error. As a plugin in Bitwig, confusion and hanging ensue. 

A window with an error message would be preferable to a crash.

I am running a local-build at b89b791 on Ubuntu 18.04.

**Comment by baconpaul** [comment]
Oh wow yeah that’s a great bug report thanks. I’ll make the tuning lib handle this case in the parser and throw a way better error message!

**Comment by baconpaul** [comment]
OK I just fixed this
If you build yourself you will need to do a fresh git submodule update --init --recursive once you re-pull master since the change is all in the subordinate tuning lib.
Thanks for the great report!

**Comment by bgins** [comment]
Yep, that did it. I tested it in Bitwig and as a standalone, and everything looks good!
